const tripGuides = [
    {
      id: 1,
      title: "Amazing Trip to Paris",
      country: "France",
      city: "Paris",
      days: 7,
      content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
      rating: 5,
      user: "John Doe",
      date: "March 25, 2024",
    },
    {
      id: 2,
      title: "Exploring Tokyo",
      country: "Japan",
      city: "Tokyo",
      days: 5,
      content: "Vestibulum ac diam sit amet quam vehicula elementum...",
      rating: 4,
      user: "Jane Smith",
      date: "March 24, 2024",
    },{
        id: 1,
        title: "Amazing Trip to Paris",
        country: "France",
        city: "Paris",
        days: 7,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
        rating: 5,
        user: "John Doe",
        date: "March 25, 2024",
      },
      {
        id: 2,
        title: "Exploring Tokyo",
        country: "Japan",
        city: "Tokyo",
        days: 5,
        content: "Vestibulum ac diam sit amet quam vehicula elementum...",
        rating: 4,
        user: "Jane Smith",
        date: "March 24, 2024",
      },{
        id: 1,
        title: "Amazing Trip to Paris",
        country: "France",
        city: "Paris",
        days: 7,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
        rating: 5,
        user: "John Doe",
        date: "March 25, 2024",
      },
      {
        id: 2,
        title: "Exploring Tokyo",
        country: "Japan",
        city: "Tokyo",
        days: 5,
        content: "Vestibulum ac diam sit amet quam vehicula elementum...",
        rating: 4,
        user: "Jane Smith",
        date: "March 24, 2024",
      },
    // Add more trip guides as needed
  ];
  
  export default tripGuides;
  